ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","D:\Prashant\Automation\fromGit\P3\aug2021\src\main\resources\uploadFile\image.PNG")
Sleep(1000)
ControlClick("Open","","Button1")
Sleep(1000)